name: nene
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  # Build
  - pip
  - setuptools_scm
  - black
  - flake8
  - make
  # Test
  - pytest
  # Run
  - myst-parser
  - jinja2
  - pyyaml
  - livereload
