# Use YAML for configuration since it allows comments like this
site_name: Nēnē
description: A no-frills static site generator
author: Leonardo Uieda
language: en
repository: leouieda/nene
menu:
  - [Home, index]
  - [Install, install]
  - [Use, manual/index]
ignore:
  - README.md
  - config-alternative.json
