# Use YAML for configuration since it allows comments like this
site_name: Nēnē
description: A no-frills static site generator
author: Leonardo Uieda
language: en
repository: leouieda/nene
menu:
  - [About, /about]
  - [Manual, /manual]
  - [Install, /manual/install.html]
ignore:
  - README.md
  - config-alternative.json
copy:
  - .nojekyll
